// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	relation_gorm "Tiktok_simple/kitex_gen/relation_gorm"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Action(ctx context.Context, req *relation_gorm.ActionRequest, callOptions ...callopt.Option) (r *relation_gorm.ActionResponse, err error)
	FollowList(ctx context.Context, req *relation_gorm.FollowListRequest, callOptions ...callopt.Option) (r *relation_gorm.FollowListResponse, err error)
	FollowerList(ctx context.Context, req *relation_gorm.FollowerListRequest, callOptions ...callopt.Option) (r *relation_gorm.FollowerListResponse, err error)
	FriendList(ctx context.Context, req *relation_gorm.FriendListRequest, callOptions ...callopt.Option) (r *relation_gorm.FriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Action(ctx context.Context, req *relation_gorm.ActionRequest, callOptions ...callopt.Option) (r *relation_gorm.ActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Action(ctx, req)
}

func (p *kUserServiceClient) FollowList(ctx context.Context, req *relation_gorm.FollowListRequest, callOptions ...callopt.Option) (r *relation_gorm.FollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowList(ctx, req)
}

func (p *kUserServiceClient) FollowerList(ctx context.Context, req *relation_gorm.FollowerListRequest, callOptions ...callopt.Option) (r *relation_gorm.FollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, req)
}

func (p *kUserServiceClient) FriendList(ctx context.Context, req *relation_gorm.FriendListRequest, callOptions ...callopt.Option) (r *relation_gorm.FriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, req)
}
